secret:
  root_username: nasi
  root_password: nasi1234
  username: nasi
  password: nasi1234
  users_list: nasi
  spec:
    affinity: # <--- You would add this block here
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
            - mongo
