secret:
  root_username: Alaa
  root_password: Alaa1234
  username: Alaa
  password: Alaa1234
  users_list: Alaa
  spec:
    affinity: # <--- You would add this block here
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
            - mongo
