apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-external-lb # A new, distinct name for this service
  labels:
    app.kubernetes.io/name: rabbitmq # This selector MUST match the labels on your RabbitMQ pods
spec:
  selector:
    app.kubernetes.io/name: rabbitmq # Match the labels on your RabbitMQ pods
  ports:
    - name: amqp
      protocol: TCP
      port: 5672       # The port the service will listen on
      targetPort: 5672 # The port on the RabbitMQ pod
    - name: management
      protocol: TCP
      port: 15672      # The port the service will listen on (for Management UI)
      targetPort: 15672 # The port on the RabbitMQ pod (for Management UI)
  type: LoadBalancer
  # Optional: For production, consider externalTrafficPolicy: Local to preserve client IP
  # externalTrafficPolicy: Local
