apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: database
spec:
  affinity: # <--- You would add this block here
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
            - postgres
  type: NodePort
  ports:
    - port: 27017
      nodePort: 30005
  selector:
    app: database
